// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// PublishParseAnime provides a mock function with given fields: ctx, id, forced
func (_m *Repository) PublishParseAnime(ctx context.Context, id int64, forced bool) error {
	ret := _m.Called(ctx, id, forced)

	if len(ret) == 0 {
		panic("no return value specified for PublishParseAnime")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, bool) error); ok {
		r0 = rf(ctx, id, forced)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PublishParseUserAnime provides a mock function with given fields: ctx, username, status, forced
func (_m *Repository) PublishParseUserAnime(ctx context.Context, username string, status string, forced bool) error {
	ret := _m.Called(ctx, username, status, forced)

	if len(ret) == 0 {
		panic("no return value specified for PublishParseUserAnime")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) error); ok {
		r0 = rf(ctx, username, status, forced)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
