// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/anime": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Anime"
                ],
                "summary": "Get anime list.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "title",
                        "name": "title",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "true",
                            "false"
                        ],
                        "type": "string",
                        "description": "nsfw",
                        "name": "nsfw",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "TV",
                            "OVA",
                            "ONA",
                            "MOVIE",
                            "SPECIAL",
                            "MUSIC"
                        ],
                        "type": "string",
                        "description": "type",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "FINISHED",
                            "RELEASING",
                            "NOT_YET"
                        ],
                        "type": "string",
                        "description": "status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "WINTER",
                            "SPRING",
                            "SUMMER",
                            "FALL"
                        ],
                        "type": "string",
                        "description": "season",
                        "name": "season",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "season year",
                        "name": "season_year",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "start mean",
                        "name": "start_mean",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "end mean",
                        "name": "end_mean",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "ID",
                            "-ID",
                            "TITLE",
                            "-TITLE",
                            "START_DATE",
                            "-START_DATE",
                            "MEAN",
                            "-MEAN",
                            "RANK",
                            "-RANK",
                            "POPULARITY",
                            "-POPULARITY",
                            "MEMBER",
                            "-MEMBER",
                            "VOTER",
                            "-VOTER"
                        ],
                        "type": "string",
                        "default": "RANK",
                        "description": "sort",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "limit",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/service.Anime"
                                            }
                                        },
                                        "meta": {
                                            "$ref": "#/definitions/service.Pagination"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/anime/{animeID}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Anime"
                ],
                "summary": "Get anime by id.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "anime id",
                        "name": "animeID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/service.Anime"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/anime/{animeID}/history": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Anime"
                ],
                "summary": "Get anime stats histories by id.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "anime id",
                        "name": "animeID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "start date (yyyy-mm-dd)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "end date (yyyy-mm-dd)",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "WEEKLY",
                            "MONTHLY",
                            "YEARLY"
                        ],
                        "type": "string",
                        "default": "MONTHLY",
                        "description": "group",
                        "name": "group",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/service.AnimeHistory"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/anime/{animeID}/update": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Anime"
                ],
                "summary": "Update anime by id.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "anime id",
                        "name": "animeID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/genres": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Genre"
                ],
                "summary": "Get genre list.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "limit",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/service.Genre"
                                            }
                                        },
                                        "meta": {
                                            "$ref": "#/definitions/service.Pagination"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/genres/{genreID}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Genre"
                ],
                "summary": "Get genre by id.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "genre id",
                        "name": "genreID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/service.Genre"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/studios": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Studio"
                ],
                "summary": "Get studio list.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "limit",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/service.Studio"
                                            }
                                        },
                                        "meta": {
                                            "$ref": "#/definitions/service.Pagination"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/studios/{studioID}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Studio"
                ],
                "summary": "Get studio by id.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "studio id",
                        "name": "studioID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/service.Studio"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/user/{username}/anime": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Anime"
                ],
                "summary": "Get user's anime.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "limit",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/service.UserAnime"
                                            }
                                        },
                                        "meta": {
                                            "$ref": "#/definitions/service.Pagination"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/user/{username}/anime/relations": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Anime"
                ],
                "summary": "Get user's anime relations.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/service.UserAnimeRelation"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/user/{username}/update": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Anime"
                ],
                "summary": "Update user's anime.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "service.Anime": {
            "type": "object",
            "properties": {
                "alternative_titles": {
                    "$ref": "#/definitions/service.alternativeTitle"
                },
                "background": {
                    "type": "string"
                },
                "broadcast": {
                    "$ref": "#/definitions/service.broadcast"
                },
                "end_date": {
                    "$ref": "#/definitions/service.date"
                },
                "episode": {
                    "$ref": "#/definitions/service.episode"
                },
                "genres": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.genre"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "mean": {
                    "type": "number"
                },
                "member": {
                    "type": "integer"
                },
                "nsfw": {
                    "type": "boolean"
                },
                "picture": {
                    "type": "string"
                },
                "pictures": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "popularity": {
                    "type": "integer"
                },
                "rank": {
                    "type": "integer"
                },
                "rating": {
                    "type": "string"
                },
                "related": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.related"
                    }
                },
                "season": {
                    "$ref": "#/definitions/service.season"
                },
                "source": {
                    "type": "string"
                },
                "start_date": {
                    "$ref": "#/definitions/service.date"
                },
                "stats": {
                    "$ref": "#/definitions/service.stats"
                },
                "status": {
                    "type": "string"
                },
                "studios": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.studio"
                    }
                },
                "synopsis": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "voter": {
                    "type": "integer"
                }
            }
        },
        "service.AnimeHistory": {
            "type": "object",
            "properties": {
                "mean": {
                    "type": "number"
                },
                "member": {
                    "type": "integer"
                },
                "month": {
                    "type": "integer"
                },
                "popularity": {
                    "type": "integer"
                },
                "rank": {
                    "type": "integer"
                },
                "user_completed": {
                    "type": "integer"
                },
                "user_dropped": {
                    "type": "integer"
                },
                "user_on_hold": {
                    "type": "integer"
                },
                "user_planned": {
                    "type": "integer"
                },
                "user_watching": {
                    "type": "integer"
                },
                "voter": {
                    "type": "integer"
                },
                "week": {
                    "type": "integer"
                },
                "year": {
                    "type": "integer"
                }
            }
        },
        "service.Genre": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "service.Pagination": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "service.Studio": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "service.UserAnime": {
            "type": "object",
            "properties": {
                "anime_id": {
                    "type": "integer"
                },
                "comment": {
                    "type": "string"
                },
                "episode": {
                    "type": "integer"
                },
                "score": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "service.UserAnimeRelation": {
            "type": "object",
            "properties": {
                "links": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.userAnimeRelationLink"
                    }
                },
                "nodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.userAnimeRelationNode"
                    }
                }
            }
        },
        "service.alternativeTitle": {
            "type": "object",
            "properties": {
                "english": {
                    "type": "string"
                },
                "japanese": {
                    "type": "string"
                },
                "synonyms": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "service.broadcast": {
            "type": "object",
            "properties": {
                "day": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "service.date": {
            "type": "object",
            "properties": {
                "day": {
                    "type": "integer"
                },
                "month": {
                    "type": "integer"
                },
                "year": {
                    "type": "integer"
                }
            }
        },
        "service.episode": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "duration": {
                    "type": "integer"
                }
            }
        },
        "service.genre": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "service.related": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "picture": {
                    "type": "string"
                },
                "relation": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "service.season": {
            "type": "object",
            "properties": {
                "season": {
                    "type": "string"
                },
                "year": {
                    "type": "integer"
                }
            }
        },
        "service.stats": {
            "type": "object",
            "properties": {
                "status": {
                    "$ref": "#/definitions/service.statsStatus"
                }
            }
        },
        "service.statsStatus": {
            "type": "object",
            "properties": {
                "completed": {
                    "type": "integer"
                },
                "dropped": {
                    "type": "integer"
                },
                "on_hold": {
                    "type": "integer"
                },
                "planned": {
                    "type": "integer"
                },
                "watching": {
                    "type": "integer"
                }
            }
        },
        "service.studio": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "service.userAnimeRelationLink": {
            "type": "object",
            "properties": {
                "anime_id1": {
                    "type": "integer"
                },
                "anime_id2": {
                    "type": "integer"
                },
                "relation": {
                    "type": "string"
                }
            }
        },
        "service.userAnimeRelationNode": {
            "type": "object",
            "properties": {
                "anime_id": {
                    "type": "integer"
                },
                "episode_count": {
                    "type": "integer"
                },
                "episode_duration": {
                    "type": "integer"
                },
                "score": {
                    "type": "number"
                },
                "season": {
                    "type": "string"
                },
                "season_year": {
                    "type": "integer"
                },
                "source": {
                    "type": "string"
                },
                "start_year": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "user_anime_score": {
                    "type": "integer"
                },
                "user_anime_status": {
                    "type": "string"
                },
                "user_episode_count": {
                    "type": "integer"
                }
            }
        },
        "utils.Response": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object"
                },
                "message": {
                    "type": "string"
                },
                "meta": {
                    "type": "object"
                },
                "status": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Akatsuki API",
	Description:      "Akatsuki API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
