// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/anime/{animeID}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Anime"
                ],
                "summary": "Get anime by id.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "anime id",
                        "name": "animeID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/service.Anime"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/anime/{animeID}/update": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Anime"
                ],
                "summary": "Update anime by id.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "anime id",
                        "name": "animeID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/mal/anime/{animeID}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MAL"
                ],
                "summary": "Get mal anime by id.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "anime id",
                        "name": "animeID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/mal.Anime"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/mal/users/{username}/animelist": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MAL"
                ],
                "summary": "Get mal user anime.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "sort",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/mal.UserAnime"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/user/{username}/anime": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Anime"
                ],
                "summary": "Get user's anime.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "limit",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/service.UserAnime"
                                            }
                                        },
                                        "meta": {
                                            "$ref": "#/definitions/service.Pagination"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/user/{username}/anime/relations": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Anime"
                ],
                "summary": "Get user's anime relations.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/service.UserAnimeRelation"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/user/{username}/update": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Anime"
                ],
                "summary": "Update user's anime.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "mal.Anime": {
            "type": "object",
            "properties": {
                "alternative_titles": {
                    "$ref": "#/definitions/mal.Titles"
                },
                "average_episode_duration": {
                    "type": "integer"
                },
                "background": {
                    "type": "string"
                },
                "broadcast": {
                    "$ref": "#/definitions/mal.Broadcast"
                },
                "created_at": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "ending_themes": {
                    "description": "undocumented",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/mal.Theme"
                    }
                },
                "genres": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/mal.Genre"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "main_picture": {
                    "$ref": "#/definitions/mal.Picture"
                },
                "mean": {
                    "type": "number"
                },
                "media_type": {
                    "type": "string"
                },
                "my_list_status": {
                    "$ref": "#/definitions/mal.AnimeListStatus"
                },
                "nsfw": {
                    "type": "string"
                },
                "num_episodes": {
                    "type": "integer"
                },
                "num_favorites": {
                    "description": "undocumented",
                    "type": "integer"
                },
                "num_list_users": {
                    "type": "integer"
                },
                "num_scoring_users": {
                    "type": "integer"
                },
                "opening_themes": {
                    "description": "undocumented",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/mal.Theme"
                    }
                },
                "pictures": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/mal.Picture"
                    }
                },
                "popularity": {
                    "type": "integer"
                },
                "rank": {
                    "type": "integer"
                },
                "rating": {
                    "type": "string"
                },
                "recommendations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/mal.RecommendedAnime"
                    }
                },
                "related_anime": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/mal.RelatedAnime"
                    }
                },
                "related_manga": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/mal.RelatedManga"
                    }
                },
                "source": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "start_season": {
                    "$ref": "#/definitions/mal.StartSeason"
                },
                "statistics": {
                    "$ref": "#/definitions/mal.Statistics"
                },
                "status": {
                    "type": "string"
                },
                "studios": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/mal.Studio"
                    }
                },
                "synopsis": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "mal.AnimeListStatus": {
            "type": "object",
            "properties": {
                "comments": {
                    "type": "string"
                },
                "finish_date": {
                    "type": "string"
                },
                "is_rewatching": {
                    "type": "boolean"
                },
                "num_episodes_watched": {
                    "type": "integer"
                },
                "num_times_rewatched": {
                    "type": "integer"
                },
                "priority": {
                    "type": "integer"
                },
                "rewatch_value": {
                    "type": "integer"
                },
                "score": {
                    "type": "integer"
                },
                "start_date": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "mal.Author": {
            "type": "object",
            "properties": {
                "node": {
                    "$ref": "#/definitions/mal.Person"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "mal.Broadcast": {
            "type": "object",
            "properties": {
                "day_of_the_week": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                }
            }
        },
        "mal.Genre": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "mal.Magazine": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "mal.Manga": {
            "type": "object",
            "properties": {
                "alternative_titles": {
                    "$ref": "#/definitions/mal.Titles"
                },
                "authors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/mal.Author"
                    }
                },
                "background": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "genres": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/mal.Genre"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "main_picture": {
                    "$ref": "#/definitions/mal.Picture"
                },
                "mean": {
                    "type": "number"
                },
                "media_type": {
                    "type": "string"
                },
                "my_list_status": {
                    "$ref": "#/definitions/mal.MangaListStatus"
                },
                "nsfw": {
                    "type": "string"
                },
                "num_chapters": {
                    "type": "integer"
                },
                "num_list_users": {
                    "type": "integer"
                },
                "num_scoring_users": {
                    "type": "integer"
                },
                "num_volumes": {
                    "type": "integer"
                },
                "pictures": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/mal.Picture"
                    }
                },
                "popularity": {
                    "type": "integer"
                },
                "rank": {
                    "type": "integer"
                },
                "recommendations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/mal.RecommendedManga"
                    }
                },
                "related_anime": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/mal.RelatedAnime"
                    }
                },
                "related_manga": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/mal.RelatedManga"
                    }
                },
                "serialization": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/mal.Serialization"
                    }
                },
                "start_date": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "synopsis": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "mal.MangaListStatus": {
            "type": "object",
            "properties": {
                "comments": {
                    "type": "string"
                },
                "is_rereading": {
                    "type": "boolean"
                },
                "num_chapters_read": {
                    "type": "integer"
                },
                "num_times_reread": {
                    "type": "integer"
                },
                "num_volumes_read": {
                    "type": "integer"
                },
                "priority": {
                    "type": "integer"
                },
                "reread_value": {
                    "type": "integer"
                },
                "score": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "mal.Person": {
            "type": "object",
            "properties": {
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "last_name": {
                    "type": "string"
                }
            }
        },
        "mal.Picture": {
            "type": "object",
            "properties": {
                "large": {
                    "type": "string"
                },
                "medium": {
                    "type": "string"
                }
            }
        },
        "mal.RecommendedAnime": {
            "type": "object",
            "properties": {
                "node": {
                    "$ref": "#/definitions/mal.Anime"
                },
                "num_recommendations": {
                    "type": "integer"
                }
            }
        },
        "mal.RecommendedManga": {
            "type": "object",
            "properties": {
                "node": {
                    "$ref": "#/definitions/mal.Manga"
                },
                "num_recommendations": {
                    "type": "integer"
                }
            }
        },
        "mal.RelatedAnime": {
            "type": "object",
            "properties": {
                "node": {
                    "$ref": "#/definitions/mal.Anime"
                },
                "relation_type": {
                    "type": "string"
                },
                "relation_type_formatted": {
                    "type": "string"
                }
            }
        },
        "mal.RelatedManga": {
            "type": "object",
            "properties": {
                "node": {
                    "$ref": "#/definitions/mal.Manga"
                },
                "relation_type": {
                    "type": "string"
                },
                "relation_type_formatted": {
                    "type": "string"
                }
            }
        },
        "mal.Serialization": {
            "type": "object",
            "properties": {
                "node": {
                    "$ref": "#/definitions/mal.Magazine"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "mal.StartSeason": {
            "type": "object",
            "properties": {
                "season": {
                    "type": "string"
                },
                "year": {
                    "type": "integer"
                }
            }
        },
        "mal.Statistics": {
            "type": "object",
            "properties": {
                "num_list_users": {
                    "type": "integer"
                },
                "status": {
                    "$ref": "#/definitions/mal.Status"
                }
            }
        },
        "mal.Status": {
            "type": "object",
            "properties": {
                "completed": {
                    "type": "integer"
                },
                "dropped": {
                    "type": "integer"
                },
                "on_hold": {
                    "type": "integer"
                },
                "plan_to_watch": {
                    "type": "integer"
                },
                "watching": {
                    "type": "integer"
                }
            }
        },
        "mal.Studio": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "mal.Theme": {
            "type": "object",
            "properties": {
                "anime_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "mal.Titles": {
            "type": "object",
            "properties": {
                "en": {
                    "type": "string"
                },
                "ja": {
                    "type": "string"
                },
                "synonyms": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "mal.UserAnime": {
            "type": "object",
            "properties": {
                "list_status": {
                    "$ref": "#/definitions/mal.AnimeListStatus"
                },
                "node": {
                    "$ref": "#/definitions/mal.Anime"
                }
            }
        },
        "service.Anime": {
            "type": "object",
            "properties": {
                "alternative_titles": {
                    "$ref": "#/definitions/service.alternativeTitle"
                },
                "background": {
                    "type": "string"
                },
                "broadcast": {
                    "$ref": "#/definitions/service.broadcast"
                },
                "end_date": {
                    "$ref": "#/definitions/service.date"
                },
                "episode": {
                    "$ref": "#/definitions/service.episode"
                },
                "genres": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.genre"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "mean": {
                    "type": "number"
                },
                "member": {
                    "type": "integer"
                },
                "nsfw": {
                    "type": "boolean"
                },
                "picture": {
                    "type": "string"
                },
                "pictures": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "popularity": {
                    "type": "integer"
                },
                "rank": {
                    "type": "integer"
                },
                "rating": {
                    "type": "string"
                },
                "related": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.related"
                    }
                },
                "season": {
                    "$ref": "#/definitions/service.season"
                },
                "source": {
                    "type": "string"
                },
                "start_date": {
                    "$ref": "#/definitions/service.date"
                },
                "stats": {
                    "$ref": "#/definitions/service.stats"
                },
                "status": {
                    "type": "string"
                },
                "studio": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.studio"
                    }
                },
                "synopsis": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "voter": {
                    "type": "integer"
                }
            }
        },
        "service.Pagination": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "service.UserAnime": {
            "type": "object",
            "properties": {
                "anime_id": {
                    "type": "integer"
                },
                "comment": {
                    "type": "string"
                },
                "episode": {
                    "type": "integer"
                },
                "score": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "service.UserAnimeRelation": {
            "type": "object",
            "properties": {
                "links": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.userAnimeRelationLink"
                    }
                },
                "nodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.userAnimeRelationNode"
                    }
                }
            }
        },
        "service.alternativeTitle": {
            "type": "object",
            "properties": {
                "english": {
                    "type": "string"
                },
                "japanese": {
                    "type": "string"
                },
                "synonyms": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "service.broadcast": {
            "type": "object",
            "properties": {
                "day": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "service.date": {
            "type": "object",
            "properties": {
                "day": {
                    "type": "integer"
                },
                "month": {
                    "type": "integer"
                },
                "year": {
                    "type": "integer"
                }
            }
        },
        "service.episode": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "duration": {
                    "type": "integer"
                }
            }
        },
        "service.genre": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "service.related": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "picture": {
                    "type": "string"
                },
                "relation": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "service.season": {
            "type": "object",
            "properties": {
                "season": {
                    "type": "string"
                },
                "year": {
                    "type": "integer"
                }
            }
        },
        "service.stats": {
            "type": "object",
            "properties": {
                "status": {
                    "$ref": "#/definitions/service.statsStatus"
                }
            }
        },
        "service.statsStatus": {
            "type": "object",
            "properties": {
                "completed": {
                    "type": "integer"
                },
                "dropped": {
                    "type": "integer"
                },
                "on_hold": {
                    "type": "integer"
                },
                "planned": {
                    "type": "integer"
                },
                "watching": {
                    "type": "integer"
                }
            }
        },
        "service.studio": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "service.userAnimeRelationLink": {
            "type": "object",
            "properties": {
                "anime_id1": {
                    "type": "integer"
                },
                "anime_id2": {
                    "type": "integer"
                },
                "relation": {
                    "type": "string"
                }
            }
        },
        "service.userAnimeRelationNode": {
            "type": "object",
            "properties": {
                "anime_id": {
                    "type": "integer"
                },
                "episode_count": {
                    "type": "integer"
                },
                "episode_duration": {
                    "type": "integer"
                },
                "score": {
                    "type": "number"
                },
                "season": {
                    "type": "string"
                },
                "season_year": {
                    "type": "integer"
                },
                "source": {
                    "type": "string"
                },
                "start_year": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "user_anime_score": {
                    "type": "integer"
                },
                "user_anime_status": {
                    "type": "string"
                },
                "user_episode_count": {
                    "type": "integer"
                }
            }
        },
        "utils.Response": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object"
                },
                "message": {
                    "type": "string"
                },
                "meta": {
                    "type": "object"
                },
                "status": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Akatsuki API",
	Description:      "Akatsuki API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
