// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api.proto

package schema

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x1a\x0fapi_anime.proto\x1a\x14api_user_anime.proto2\x9a\x01\n" +
	"\x03API\x12;\n" +
	"\fGetAnimeByID\x12\x14.GetAnimeByIDRequest\x1a\x15.GetAnimeByIDResponse\x12V\n" +
	"\x15GetUserAnimeRelations\x12\x1d.GetUserAnimeRelationsRequest\x1a\x1e.GetUserAnimeRelationsResponseB9Z7github.com/rl404/akatsuki/internal/delivery/grpc/schemab\x06proto3"

var file_api_proto_goTypes = []any{
	(*GetAnimeByIDRequest)(nil),           // 0: GetAnimeByIDRequest
	(*GetUserAnimeRelationsRequest)(nil),  // 1: GetUserAnimeRelationsRequest
	(*GetAnimeByIDResponse)(nil),          // 2: GetAnimeByIDResponse
	(*GetUserAnimeRelationsResponse)(nil), // 3: GetUserAnimeRelationsResponse
}
var file_api_proto_depIdxs = []int32{
	0, // 0: API.GetAnimeByID:input_type -> GetAnimeByIDRequest
	1, // 1: API.GetUserAnimeRelations:input_type -> GetUserAnimeRelationsRequest
	2, // 2: API.GetAnimeByID:output_type -> GetAnimeByIDResponse
	3, // 3: API.GetUserAnimeRelations:output_type -> GetUserAnimeRelationsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	file_api_anime_proto_init()
	file_api_user_anime_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
