// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: api.proto

package schema

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	API_GetAnimeByID_FullMethodName          = "/API/GetAnimeByID"
	API_GetUserAnimeRelations_FullMethodName = "/API/GetUserAnimeRelations"
)

// APIClient is the client API for API service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// API service.
type APIClient interface {
	// GetAnimeByID to get anime by id.
	GetAnimeByID(ctx context.Context, in *GetAnimeByIDRequest, opts ...grpc.CallOption) (*GetAnimeByIDResponse, error)
	// GetUserAnimeRelations to get user anime relations.
	GetUserAnimeRelations(ctx context.Context, in *GetUserAnimeRelationsRequest, opts ...grpc.CallOption) (*GetUserAnimeRelationsResponse, error)
}

type aPIClient struct {
	cc grpc.ClientConnInterface
}

func NewAPIClient(cc grpc.ClientConnInterface) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) GetAnimeByID(ctx context.Context, in *GetAnimeByIDRequest, opts ...grpc.CallOption) (*GetAnimeByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAnimeByIDResponse)
	err := c.cc.Invoke(ctx, API_GetAnimeByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetUserAnimeRelations(ctx context.Context, in *GetUserAnimeRelationsRequest, opts ...grpc.CallOption) (*GetUserAnimeRelationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserAnimeRelationsResponse)
	err := c.cc.Invoke(ctx, API_GetUserAnimeRelations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIServer is the server API for API service.
// All implementations must embed UnimplementedAPIServer
// for forward compatibility.
//
// API service.
type APIServer interface {
	// GetAnimeByID to get anime by id.
	GetAnimeByID(context.Context, *GetAnimeByIDRequest) (*GetAnimeByIDResponse, error)
	// GetUserAnimeRelations to get user anime relations.
	GetUserAnimeRelations(context.Context, *GetUserAnimeRelationsRequest) (*GetUserAnimeRelationsResponse, error)
	mustEmbedUnimplementedAPIServer()
}

// UnimplementedAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAPIServer struct{}

func (UnimplementedAPIServer) GetAnimeByID(context.Context, *GetAnimeByIDRequest) (*GetAnimeByIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAnimeByID not implemented")
}
func (UnimplementedAPIServer) GetUserAnimeRelations(context.Context, *GetUserAnimeRelationsRequest) (*GetUserAnimeRelationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserAnimeRelations not implemented")
}
func (UnimplementedAPIServer) mustEmbedUnimplementedAPIServer() {}
func (UnimplementedAPIServer) testEmbeddedByValue()             {}

// UnsafeAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to APIServer will
// result in compilation errors.
type UnsafeAPIServer interface {
	mustEmbedUnimplementedAPIServer()
}

func RegisterAPIServer(s grpc.ServiceRegistrar, srv APIServer) {
	// If the following call panics, it indicates UnimplementedAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&API_ServiceDesc, srv)
}

func _API_GetAnimeByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAnimeByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetAnimeByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: API_GetAnimeByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetAnimeByID(ctx, req.(*GetAnimeByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetUserAnimeRelations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserAnimeRelationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetUserAnimeRelations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: API_GetUserAnimeRelations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetUserAnimeRelations(ctx, req.(*GetUserAnimeRelationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// API_ServiceDesc is the grpc.ServiceDesc for API service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var API_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAnimeByID",
			Handler:    _API_GetAnimeByID_Handler,
		},
		{
			MethodName: "GetUserAnimeRelations",
			Handler:    _API_GetUserAnimeRelations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
