// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api_user_anime.proto

package schema

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserAnimeRelationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAnimeRelationsRequest) Reset() {
	*x = GetUserAnimeRelationsRequest{}
	mi := &file_api_user_anime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAnimeRelationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAnimeRelationsRequest) ProtoMessage() {}

func (x *GetUserAnimeRelationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_anime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAnimeRelationsRequest.ProtoReflect.Descriptor instead.
func (*GetUserAnimeRelationsRequest) Descriptor() ([]byte, []int) {
	return file_api_user_anime_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserAnimeRelationsRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetUserAnimeRelationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *UserAnimeRelation     `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAnimeRelationsResponse) Reset() {
	*x = GetUserAnimeRelationsResponse{}
	mi := &file_api_user_anime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAnimeRelationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAnimeRelationsResponse) ProtoMessage() {}

func (x *GetUserAnimeRelationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_anime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAnimeRelationsResponse.ProtoReflect.Descriptor instead.
func (*GetUserAnimeRelationsResponse) Descriptor() ([]byte, []int) {
	return file_api_user_anime_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserAnimeRelationsResponse) GetData() *UserAnimeRelation {
	if x != nil {
		return x.Data
	}
	return nil
}

type UserAnimeRelation struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Nodes         []*UserAnimeRelationNode `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Links         []*UserAnimeRelationLink `protobuf:"bytes,2,rep,name=links,proto3" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAnimeRelation) Reset() {
	*x = UserAnimeRelation{}
	mi := &file_api_user_anime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAnimeRelation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAnimeRelation) ProtoMessage() {}

func (x *UserAnimeRelation) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_anime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAnimeRelation.ProtoReflect.Descriptor instead.
func (*UserAnimeRelation) Descriptor() ([]byte, []int) {
	return file_api_user_anime_proto_rawDescGZIP(), []int{2}
}

func (x *UserAnimeRelation) GetNodes() []*UserAnimeRelationNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *UserAnimeRelation) GetLinks() []*UserAnimeRelationLink {
	if x != nil {
		return x.Links
	}
	return nil
}

type UserAnimeRelationNode struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AnimeId          int64                  `protobuf:"varint,1,opt,name=anime_id,json=animeId,proto3" json:"anime_id,omitempty"`
	Title            string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Status           Status                 `protobuf:"varint,3,opt,name=status,proto3,enum=Status" json:"status,omitempty"`
	Score            float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`
	Type             Type                   `protobuf:"varint,5,opt,name=type,proto3,enum=Type" json:"type,omitempty"`
	Source           Source                 `protobuf:"varint,6,opt,name=source,proto3,enum=Source" json:"source,omitempty"`
	EpisodeCount     int32                  `protobuf:"varint,7,opt,name=episode_count,json=episodeCount,proto3" json:"episode_count,omitempty"`
	EpisodeDuration  int32                  `protobuf:"varint,8,opt,name=episode_duration,json=episodeDuration,proto3" json:"episode_duration,omitempty"`
	StartYear        int32                  `protobuf:"varint,9,opt,name=start_year,json=startYear,proto3" json:"start_year,omitempty"`
	Season           Season                 `protobuf:"varint,10,opt,name=season,proto3,enum=Season" json:"season,omitempty"`
	SeasonYear       int32                  `protobuf:"varint,11,opt,name=season_year,json=seasonYear,proto3" json:"season_year,omitempty"`
	UserAnimeStatus  UserAnimeStatus        `protobuf:"varint,12,opt,name=user_anime_status,json=userAnimeStatus,proto3,enum=UserAnimeStatus" json:"user_anime_status,omitempty"`
	UserAnimeScore   int32                  `protobuf:"varint,13,opt,name=user_anime_score,json=userAnimeScore,proto3" json:"user_anime_score,omitempty"`
	UserEpisodeCount int32                  `protobuf:"varint,14,opt,name=user_episode_count,json=userEpisodeCount,proto3" json:"user_episode_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserAnimeRelationNode) Reset() {
	*x = UserAnimeRelationNode{}
	mi := &file_api_user_anime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAnimeRelationNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAnimeRelationNode) ProtoMessage() {}

func (x *UserAnimeRelationNode) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_anime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAnimeRelationNode.ProtoReflect.Descriptor instead.
func (*UserAnimeRelationNode) Descriptor() ([]byte, []int) {
	return file_api_user_anime_proto_rawDescGZIP(), []int{3}
}

func (x *UserAnimeRelationNode) GetAnimeId() int64 {
	if x != nil {
		return x.AnimeId
	}
	return 0
}

func (x *UserAnimeRelationNode) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UserAnimeRelationNode) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNKNOWN
}

func (x *UserAnimeRelationNode) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *UserAnimeRelationNode) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_TYPE_UNKNOWN
}

func (x *UserAnimeRelationNode) GetSource() Source {
	if x != nil {
		return x.Source
	}
	return Source_SOURCE_UNKNOWN
}

func (x *UserAnimeRelationNode) GetEpisodeCount() int32 {
	if x != nil {
		return x.EpisodeCount
	}
	return 0
}

func (x *UserAnimeRelationNode) GetEpisodeDuration() int32 {
	if x != nil {
		return x.EpisodeDuration
	}
	return 0
}

func (x *UserAnimeRelationNode) GetStartYear() int32 {
	if x != nil {
		return x.StartYear
	}
	return 0
}

func (x *UserAnimeRelationNode) GetSeason() Season {
	if x != nil {
		return x.Season
	}
	return Season_SEASON_UNKNOWN
}

func (x *UserAnimeRelationNode) GetSeasonYear() int32 {
	if x != nil {
		return x.SeasonYear
	}
	return 0
}

func (x *UserAnimeRelationNode) GetUserAnimeStatus() UserAnimeStatus {
	if x != nil {
		return x.UserAnimeStatus
	}
	return UserAnimeStatus_USER_ANIME_STATUS_UNKNOWN
}

func (x *UserAnimeRelationNode) GetUserAnimeScore() int32 {
	if x != nil {
		return x.UserAnimeScore
	}
	return 0
}

func (x *UserAnimeRelationNode) GetUserEpisodeCount() int32 {
	if x != nil {
		return x.UserEpisodeCount
	}
	return 0
}

type UserAnimeRelationLink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnimeId1      int64                  `protobuf:"varint,1,opt,name=anime_id1,json=animeId1,proto3" json:"anime_id1,omitempty"`
	AnimeId2      int64                  `protobuf:"varint,2,opt,name=anime_id2,json=animeId2,proto3" json:"anime_id2,omitempty"`
	Relation      Relation               `protobuf:"varint,3,opt,name=relation,proto3,enum=Relation" json:"relation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAnimeRelationLink) Reset() {
	*x = UserAnimeRelationLink{}
	mi := &file_api_user_anime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAnimeRelationLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAnimeRelationLink) ProtoMessage() {}

func (x *UserAnimeRelationLink) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_anime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAnimeRelationLink.ProtoReflect.Descriptor instead.
func (*UserAnimeRelationLink) Descriptor() ([]byte, []int) {
	return file_api_user_anime_proto_rawDescGZIP(), []int{4}
}

func (x *UserAnimeRelationLink) GetAnimeId1() int64 {
	if x != nil {
		return x.AnimeId1
	}
	return 0
}

func (x *UserAnimeRelationLink) GetAnimeId2() int64 {
	if x != nil {
		return x.AnimeId2
	}
	return 0
}

func (x *UserAnimeRelationLink) GetRelation() Relation {
	if x != nil {
		return x.Relation
	}
	return Relation_RELATION_UNKNOWN
}

var File_api_user_anime_proto protoreflect.FileDescriptor

const file_api_user_anime_proto_rawDesc = "" +
	"\n" +
	"\x14api_user_anime.proto\x1a\n" +
	"enum.proto\":\n" +
	"\x1cGetUserAnimeRelationsRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"G\n" +
	"\x1dGetUserAnimeRelationsResponse\x12&\n" +
	"\x04data\x18\x01 \x01(\v2\x12.UserAnimeRelationR\x04data\"o\n" +
	"\x11UserAnimeRelation\x12,\n" +
	"\x05nodes\x18\x01 \x03(\v2\x16.UserAnimeRelationNodeR\x05nodes\x12,\n" +
	"\x05links\x18\x02 \x03(\v2\x16.UserAnimeRelationLinkR\x05links\"\x82\x04\n" +
	"\x15UserAnimeRelationNode\x12\x19\n" +
	"\banime_id\x18\x01 \x01(\x03R\aanimeId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1f\n" +
	"\x06status\x18\x03 \x01(\x0e2\a.StatusR\x06status\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\x12\x19\n" +
	"\x04type\x18\x05 \x01(\x0e2\x05.TypeR\x04type\x12\x1f\n" +
	"\x06source\x18\x06 \x01(\x0e2\a.SourceR\x06source\x12#\n" +
	"\repisode_count\x18\a \x01(\x05R\fepisodeCount\x12)\n" +
	"\x10episode_duration\x18\b \x01(\x05R\x0fepisodeDuration\x12\x1d\n" +
	"\n" +
	"start_year\x18\t \x01(\x05R\tstartYear\x12\x1f\n" +
	"\x06season\x18\n" +
	" \x01(\x0e2\a.SeasonR\x06season\x12\x1f\n" +
	"\vseason_year\x18\v \x01(\x05R\n" +
	"seasonYear\x12<\n" +
	"\x11user_anime_status\x18\f \x01(\x0e2\x10.UserAnimeStatusR\x0fuserAnimeStatus\x12(\n" +
	"\x10user_anime_score\x18\r \x01(\x05R\x0euserAnimeScore\x12,\n" +
	"\x12user_episode_count\x18\x0e \x01(\x05R\x10userEpisodeCount\"x\n" +
	"\x15UserAnimeRelationLink\x12\x1b\n" +
	"\tanime_id1\x18\x01 \x01(\x03R\banimeId1\x12\x1b\n" +
	"\tanime_id2\x18\x02 \x01(\x03R\banimeId2\x12%\n" +
	"\brelation\x18\x03 \x01(\x0e2\t.RelationR\brelationB9Z7github.com/rl404/akatsuki/internal/delivery/grpc/schemab\x06proto3"

var (
	file_api_user_anime_proto_rawDescOnce sync.Once
	file_api_user_anime_proto_rawDescData []byte
)

func file_api_user_anime_proto_rawDescGZIP() []byte {
	file_api_user_anime_proto_rawDescOnce.Do(func() {
		file_api_user_anime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_user_anime_proto_rawDesc), len(file_api_user_anime_proto_rawDesc)))
	})
	return file_api_user_anime_proto_rawDescData
}

var file_api_user_anime_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_user_anime_proto_goTypes = []any{
	(*GetUserAnimeRelationsRequest)(nil),  // 0: GetUserAnimeRelationsRequest
	(*GetUserAnimeRelationsResponse)(nil), // 1: GetUserAnimeRelationsResponse
	(*UserAnimeRelation)(nil),             // 2: UserAnimeRelation
	(*UserAnimeRelationNode)(nil),         // 3: UserAnimeRelationNode
	(*UserAnimeRelationLink)(nil),         // 4: UserAnimeRelationLink
	(Status)(0),                           // 5: Status
	(Type)(0),                             // 6: Type
	(Source)(0),                           // 7: Source
	(Season)(0),                           // 8: Season
	(UserAnimeStatus)(0),                  // 9: UserAnimeStatus
	(Relation)(0),                         // 10: Relation
}
var file_api_user_anime_proto_depIdxs = []int32{
	2,  // 0: GetUserAnimeRelationsResponse.data:type_name -> UserAnimeRelation
	3,  // 1: UserAnimeRelation.nodes:type_name -> UserAnimeRelationNode
	4,  // 2: UserAnimeRelation.links:type_name -> UserAnimeRelationLink
	5,  // 3: UserAnimeRelationNode.status:type_name -> Status
	6,  // 4: UserAnimeRelationNode.type:type_name -> Type
	7,  // 5: UserAnimeRelationNode.source:type_name -> Source
	8,  // 6: UserAnimeRelationNode.season:type_name -> Season
	9,  // 7: UserAnimeRelationNode.user_anime_status:type_name -> UserAnimeStatus
	10, // 8: UserAnimeRelationLink.relation:type_name -> Relation
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_user_anime_proto_init() }
func file_api_user_anime_proto_init() {
	if File_api_user_anime_proto != nil {
		return
	}
	file_enum_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_user_anime_proto_rawDesc), len(file_api_user_anime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_user_anime_proto_goTypes,
		DependencyIndexes: file_api_user_anime_proto_depIdxs,
		MessageInfos:      file_api_user_anime_proto_msgTypes,
	}.Build()
	File_api_user_anime_proto = out.File
	file_api_user_anime_proto_goTypes = nil
	file_api_user_anime_proto_depIdxs = nil
}
