// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api_anime.proto

package schema

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAnimeByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnimeByIDRequest) Reset() {
	*x = GetAnimeByIDRequest{}
	mi := &file_api_anime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnimeByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnimeByIDRequest) ProtoMessage() {}

func (x *GetAnimeByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_anime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnimeByIDRequest.ProtoReflect.Descriptor instead.
func (*GetAnimeByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_anime_proto_rawDescGZIP(), []int{0}
}

func (x *GetAnimeByIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAnimeByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Anime                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnimeByIDResponse) Reset() {
	*x = GetAnimeByIDResponse{}
	mi := &file_api_anime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnimeByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnimeByIDResponse) ProtoMessage() {}

func (x *GetAnimeByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_anime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnimeByIDResponse.ProtoReflect.Descriptor instead.
func (*GetAnimeByIDResponse) Descriptor() ([]byte, []int) {
	return file_api_anime_proto_rawDescGZIP(), []int{1}
}

func (x *GetAnimeByIDResponse) GetData() *Anime {
	if x != nil {
		return x.Data
	}
	return nil
}

type Anime struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title             string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	AlternativeTitles *AlternativeTitles     `protobuf:"bytes,3,opt,name=alternative_titles,json=alternativeTitles,proto3" json:"alternative_titles,omitempty"`
	Picture           string                 `protobuf:"bytes,4,opt,name=picture,proto3" json:"picture,omitempty"`
	StartDate         *Date                  `protobuf:"bytes,5,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate           *Date                  `protobuf:"bytes,6,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Synopsis          string                 `protobuf:"bytes,7,opt,name=synopsis,proto3" json:"synopsis,omitempty"`
	Background        string                 `protobuf:"bytes,8,opt,name=background,proto3" json:"background,omitempty"`
	Nsfw              bool                   `protobuf:"varint,9,opt,name=nsfw,proto3" json:"nsfw,omitempty"`
	Type              Type                   `protobuf:"varint,10,opt,name=type,proto3,enum=Type" json:"type,omitempty"`
	Status            Status                 `protobuf:"varint,11,opt,name=status,proto3,enum=Status" json:"status,omitempty"`
	Episode           *Episode               `protobuf:"bytes,12,opt,name=episode,proto3" json:"episode,omitempty"`
	Season            *AnimeSeason           `protobuf:"bytes,13,opt,name=season,proto3" json:"season,omitempty"`
	Broadcast         *Broadcast             `protobuf:"bytes,14,opt,name=broadcast,proto3" json:"broadcast,omitempty"`
	Source            Source                 `protobuf:"varint,15,opt,name=source,proto3,enum=Source" json:"source,omitempty"`
	Rating            Rating                 `protobuf:"varint,16,opt,name=rating,proto3,enum=Rating" json:"rating,omitempty"`
	Mean              float64                `protobuf:"fixed64,17,opt,name=mean,proto3" json:"mean,omitempty"`
	Rank              int32                  `protobuf:"varint,18,opt,name=rank,proto3" json:"rank,omitempty"`
	Popularity        int32                  `protobuf:"varint,19,opt,name=popularity,proto3" json:"popularity,omitempty"`
	Member            int32                  `protobuf:"varint,20,opt,name=member,proto3" json:"member,omitempty"`
	Voter             int32                  `protobuf:"varint,21,opt,name=voter,proto3" json:"voter,omitempty"`
	Stats             *Stats                 `protobuf:"bytes,22,opt,name=stats,proto3" json:"stats,omitempty"`
	Genres            []*AnimeGenre          `protobuf:"bytes,23,rep,name=genres,proto3" json:"genres,omitempty"`
	Pictures          []string               `protobuf:"bytes,24,rep,name=pictures,proto3" json:"pictures,omitempty"`
	Related           []*AnimeRelated        `protobuf:"bytes,25,rep,name=related,proto3" json:"related,omitempty"`
	Studios           []*AnimeStudio         `protobuf:"bytes,26,rep,name=studios,proto3" json:"studios,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Anime) Reset() {
	*x = Anime{}
	mi := &file_api_anime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Anime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Anime) ProtoMessage() {}

func (x *Anime) ProtoReflect() protoreflect.Message {
	mi := &file_api_anime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Anime.ProtoReflect.Descriptor instead.
func (*Anime) Descriptor() ([]byte, []int) {
	return file_api_anime_proto_rawDescGZIP(), []int{2}
}

func (x *Anime) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Anime) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Anime) GetAlternativeTitles() *AlternativeTitles {
	if x != nil {
		return x.AlternativeTitles
	}
	return nil
}

func (x *Anime) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

func (x *Anime) GetStartDate() *Date {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *Anime) GetEndDate() *Date {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *Anime) GetSynopsis() string {
	if x != nil {
		return x.Synopsis
	}
	return ""
}

func (x *Anime) GetBackground() string {
	if x != nil {
		return x.Background
	}
	return ""
}

func (x *Anime) GetNsfw() bool {
	if x != nil {
		return x.Nsfw
	}
	return false
}

func (x *Anime) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_TYPE_UNKNOWN
}

func (x *Anime) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNKNOWN
}

func (x *Anime) GetEpisode() *Episode {
	if x != nil {
		return x.Episode
	}
	return nil
}

func (x *Anime) GetSeason() *AnimeSeason {
	if x != nil {
		return x.Season
	}
	return nil
}

func (x *Anime) GetBroadcast() *Broadcast {
	if x != nil {
		return x.Broadcast
	}
	return nil
}

func (x *Anime) GetSource() Source {
	if x != nil {
		return x.Source
	}
	return Source_SOURCE_UNKNOWN
}

func (x *Anime) GetRating() Rating {
	if x != nil {
		return x.Rating
	}
	return Rating_RATING_UNKNOWN
}

func (x *Anime) GetMean() float64 {
	if x != nil {
		return x.Mean
	}
	return 0
}

func (x *Anime) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *Anime) GetPopularity() int32 {
	if x != nil {
		return x.Popularity
	}
	return 0
}

func (x *Anime) GetMember() int32 {
	if x != nil {
		return x.Member
	}
	return 0
}

func (x *Anime) GetVoter() int32 {
	if x != nil {
		return x.Voter
	}
	return 0
}

func (x *Anime) GetStats() *Stats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *Anime) GetGenres() []*AnimeGenre {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *Anime) GetPictures() []string {
	if x != nil {
		return x.Pictures
	}
	return nil
}

func (x *Anime) GetRelated() []*AnimeRelated {
	if x != nil {
		return x.Related
	}
	return nil
}

func (x *Anime) GetStudios() []*AnimeStudio {
	if x != nil {
		return x.Studios
	}
	return nil
}

type AlternativeTitles struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Synonyms      []string               `protobuf:"bytes,1,rep,name=synonyms,proto3" json:"synonyms,omitempty"`
	English       string                 `protobuf:"bytes,2,opt,name=english,proto3" json:"english,omitempty"`
	Japanese      string                 `protobuf:"bytes,3,opt,name=japanese,proto3" json:"japanese,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlternativeTitles) Reset() {
	*x = AlternativeTitles{}
	mi := &file_api_anime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlternativeTitles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlternativeTitles) ProtoMessage() {}

func (x *AlternativeTitles) ProtoReflect() protoreflect.Message {
	mi := &file_api_anime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlternativeTitles.ProtoReflect.Descriptor instead.
func (*AlternativeTitles) Descriptor() ([]byte, []int) {
	return file_api_anime_proto_rawDescGZIP(), []int{3}
}

func (x *AlternativeTitles) GetSynonyms() []string {
	if x != nil {
		return x.Synonyms
	}
	return nil
}

func (x *AlternativeTitles) GetEnglish() string {
	if x != nil {
		return x.English
	}
	return ""
}

func (x *AlternativeTitles) GetJapanese() string {
	if x != nil {
		return x.Japanese
	}
	return ""
}

type Date struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	Day           int32                  `protobuf:"varint,3,opt,name=day,proto3" json:"day,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Date) Reset() {
	*x = Date{}
	mi := &file_api_anime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Date) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Date) ProtoMessage() {}

func (x *Date) ProtoReflect() protoreflect.Message {
	mi := &file_api_anime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Date.ProtoReflect.Descriptor instead.
func (*Date) Descriptor() ([]byte, []int) {
	return file_api_anime_proto_rawDescGZIP(), []int{4}
}

func (x *Date) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Date) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *Date) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

type Episode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Duration      int32                  `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Episode) Reset() {
	*x = Episode{}
	mi := &file_api_anime_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Episode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Episode) ProtoMessage() {}

func (x *Episode) ProtoReflect() protoreflect.Message {
	mi := &file_api_anime_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Episode.ProtoReflect.Descriptor instead.
func (*Episode) Descriptor() ([]byte, []int) {
	return file_api_anime_proto_rawDescGZIP(), []int{5}
}

func (x *Episode) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Episode) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type AnimeSeason struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Season        Season                 `protobuf:"varint,1,opt,name=season,proto3,enum=Season" json:"season,omitempty"`
	Year          int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnimeSeason) Reset() {
	*x = AnimeSeason{}
	mi := &file_api_anime_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnimeSeason) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimeSeason) ProtoMessage() {}

func (x *AnimeSeason) ProtoReflect() protoreflect.Message {
	mi := &file_api_anime_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimeSeason.ProtoReflect.Descriptor instead.
func (*AnimeSeason) Descriptor() ([]byte, []int) {
	return file_api_anime_proto_rawDescGZIP(), []int{6}
}

func (x *AnimeSeason) GetSeason() Season {
	if x != nil {
		return x.Season
	}
	return Season_SEASON_UNKNOWN
}

func (x *AnimeSeason) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type Broadcast struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Day           Day                    `protobuf:"varint,1,opt,name=day,proto3,enum=Day" json:"day,omitempty"`
	Time          string                 `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Broadcast) Reset() {
	*x = Broadcast{}
	mi := &file_api_anime_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Broadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Broadcast) ProtoMessage() {}

func (x *Broadcast) ProtoReflect() protoreflect.Message {
	mi := &file_api_anime_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Broadcast.ProtoReflect.Descriptor instead.
func (*Broadcast) Descriptor() ([]byte, []int) {
	return file_api_anime_proto_rawDescGZIP(), []int{7}
}

func (x *Broadcast) GetDay() Day {
	if x != nil {
		return x.Day
	}
	return Day_DAY_UNKNOWN
}

func (x *Broadcast) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

type Stats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *StatsStatus           `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stats) Reset() {
	*x = Stats{}
	mi := &file_api_anime_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stats) ProtoMessage() {}

func (x *Stats) ProtoReflect() protoreflect.Message {
	mi := &file_api_anime_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stats.ProtoReflect.Descriptor instead.
func (*Stats) Descriptor() ([]byte, []int) {
	return file_api_anime_proto_rawDescGZIP(), []int{8}
}

func (x *Stats) GetStatus() *StatsStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type StatsStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Watching      int32                  `protobuf:"varint,1,opt,name=watching,proto3" json:"watching,omitempty"`
	Completed     int32                  `protobuf:"varint,2,opt,name=completed,proto3" json:"completed,omitempty"`
	OnHold        int32                  `protobuf:"varint,3,opt,name=on_hold,json=onHold,proto3" json:"on_hold,omitempty"`
	Dropped       int32                  `protobuf:"varint,4,opt,name=dropped,proto3" json:"dropped,omitempty"`
	Planned       int32                  `protobuf:"varint,5,opt,name=planned,proto3" json:"planned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsStatus) Reset() {
	*x = StatsStatus{}
	mi := &file_api_anime_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsStatus) ProtoMessage() {}

func (x *StatsStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_anime_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsStatus.ProtoReflect.Descriptor instead.
func (*StatsStatus) Descriptor() ([]byte, []int) {
	return file_api_anime_proto_rawDescGZIP(), []int{9}
}

func (x *StatsStatus) GetWatching() int32 {
	if x != nil {
		return x.Watching
	}
	return 0
}

func (x *StatsStatus) GetCompleted() int32 {
	if x != nil {
		return x.Completed
	}
	return 0
}

func (x *StatsStatus) GetOnHold() int32 {
	if x != nil {
		return x.OnHold
	}
	return 0
}

func (x *StatsStatus) GetDropped() int32 {
	if x != nil {
		return x.Dropped
	}
	return 0
}

func (x *StatsStatus) GetPlanned() int32 {
	if x != nil {
		return x.Planned
	}
	return 0
}

type AnimeGenre struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnimeGenre) Reset() {
	*x = AnimeGenre{}
	mi := &file_api_anime_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnimeGenre) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimeGenre) ProtoMessage() {}

func (x *AnimeGenre) ProtoReflect() protoreflect.Message {
	mi := &file_api_anime_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimeGenre.ProtoReflect.Descriptor instead.
func (*AnimeGenre) Descriptor() ([]byte, []int) {
	return file_api_anime_proto_rawDescGZIP(), []int{10}
}

func (x *AnimeGenre) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AnimeGenre) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AnimeRelated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Picture       string                 `protobuf:"bytes,3,opt,name=picture,proto3" json:"picture,omitempty"`
	Relation      Relation               `protobuf:"varint,4,opt,name=relation,proto3,enum=Relation" json:"relation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnimeRelated) Reset() {
	*x = AnimeRelated{}
	mi := &file_api_anime_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnimeRelated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimeRelated) ProtoMessage() {}

func (x *AnimeRelated) ProtoReflect() protoreflect.Message {
	mi := &file_api_anime_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimeRelated.ProtoReflect.Descriptor instead.
func (*AnimeRelated) Descriptor() ([]byte, []int) {
	return file_api_anime_proto_rawDescGZIP(), []int{11}
}

func (x *AnimeRelated) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AnimeRelated) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AnimeRelated) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

func (x *AnimeRelated) GetRelation() Relation {
	if x != nil {
		return x.Relation
	}
	return Relation_RELATION_UNKNOWN
}

type AnimeStudio struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnimeStudio) Reset() {
	*x = AnimeStudio{}
	mi := &file_api_anime_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnimeStudio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimeStudio) ProtoMessage() {}

func (x *AnimeStudio) ProtoReflect() protoreflect.Message {
	mi := &file_api_anime_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimeStudio.ProtoReflect.Descriptor instead.
func (*AnimeStudio) Descriptor() ([]byte, []int) {
	return file_api_anime_proto_rawDescGZIP(), []int{12}
}

func (x *AnimeStudio) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AnimeStudio) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_api_anime_proto protoreflect.FileDescriptor

const file_api_anime_proto_rawDesc = "" +
	"\n" +
	"\x0fapi_anime.proto\x1a\n" +
	"enum.proto\"%\n" +
	"\x13GetAnimeByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"2\n" +
	"\x14GetAnimeByIDResponse\x12\x1a\n" +
	"\x04data\x18\x01 \x01(\v2\x06.AnimeR\x04data\"\xba\x06\n" +
	"\x05Anime\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12A\n" +
	"\x12alternative_titles\x18\x03 \x01(\v2\x12.AlternativeTitlesR\x11alternativeTitles\x12\x18\n" +
	"\apicture\x18\x04 \x01(\tR\apicture\x12$\n" +
	"\n" +
	"start_date\x18\x05 \x01(\v2\x05.DateR\tstartDate\x12 \n" +
	"\bend_date\x18\x06 \x01(\v2\x05.DateR\aendDate\x12\x1a\n" +
	"\bsynopsis\x18\a \x01(\tR\bsynopsis\x12\x1e\n" +
	"\n" +
	"background\x18\b \x01(\tR\n" +
	"background\x12\x12\n" +
	"\x04nsfw\x18\t \x01(\bR\x04nsfw\x12\x19\n" +
	"\x04type\x18\n" +
	" \x01(\x0e2\x05.TypeR\x04type\x12\x1f\n" +
	"\x06status\x18\v \x01(\x0e2\a.StatusR\x06status\x12\"\n" +
	"\aepisode\x18\f \x01(\v2\b.EpisodeR\aepisode\x12$\n" +
	"\x06season\x18\r \x01(\v2\f.AnimeSeasonR\x06season\x12(\n" +
	"\tbroadcast\x18\x0e \x01(\v2\n" +
	".BroadcastR\tbroadcast\x12\x1f\n" +
	"\x06source\x18\x0f \x01(\x0e2\a.SourceR\x06source\x12\x1f\n" +
	"\x06rating\x18\x10 \x01(\x0e2\a.RatingR\x06rating\x12\x12\n" +
	"\x04mean\x18\x11 \x01(\x01R\x04mean\x12\x12\n" +
	"\x04rank\x18\x12 \x01(\x05R\x04rank\x12\x1e\n" +
	"\n" +
	"popularity\x18\x13 \x01(\x05R\n" +
	"popularity\x12\x16\n" +
	"\x06member\x18\x14 \x01(\x05R\x06member\x12\x14\n" +
	"\x05voter\x18\x15 \x01(\x05R\x05voter\x12\x1c\n" +
	"\x05stats\x18\x16 \x01(\v2\x06.StatsR\x05stats\x12#\n" +
	"\x06genres\x18\x17 \x03(\v2\v.AnimeGenreR\x06genres\x12\x1a\n" +
	"\bpictures\x18\x18 \x03(\tR\bpictures\x12'\n" +
	"\arelated\x18\x19 \x03(\v2\r.AnimeRelatedR\arelated\x12&\n" +
	"\astudios\x18\x1a \x03(\v2\f.AnimeStudioR\astudios\"e\n" +
	"\x11AlternativeTitles\x12\x1a\n" +
	"\bsynonyms\x18\x01 \x03(\tR\bsynonyms\x12\x18\n" +
	"\aenglish\x18\x02 \x01(\tR\aenglish\x12\x1a\n" +
	"\bjapanese\x18\x03 \x01(\tR\bjapanese\"B\n" +
	"\x04Date\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\x05R\x05month\x12\x10\n" +
	"\x03day\x18\x03 \x01(\x05R\x03day\";\n" +
	"\aEpisode\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x12\x1a\n" +
	"\bduration\x18\x02 \x01(\x05R\bduration\"B\n" +
	"\vAnimeSeason\x12\x1f\n" +
	"\x06season\x18\x01 \x01(\x0e2\a.SeasonR\x06season\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\"7\n" +
	"\tBroadcast\x12\x16\n" +
	"\x03day\x18\x01 \x01(\x0e2\x04.DayR\x03day\x12\x12\n" +
	"\x04time\x18\x02 \x01(\tR\x04time\"-\n" +
	"\x05Stats\x12$\n" +
	"\x06status\x18\x01 \x01(\v2\f.StatsStatusR\x06status\"\x94\x01\n" +
	"\vStatsStatus\x12\x1a\n" +
	"\bwatching\x18\x01 \x01(\x05R\bwatching\x12\x1c\n" +
	"\tcompleted\x18\x02 \x01(\x05R\tcompleted\x12\x17\n" +
	"\aon_hold\x18\x03 \x01(\x05R\x06onHold\x12\x18\n" +
	"\adropped\x18\x04 \x01(\x05R\adropped\x12\x18\n" +
	"\aplanned\x18\x05 \x01(\x05R\aplanned\"0\n" +
	"\n" +
	"AnimeGenre\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"u\n" +
	"\fAnimeRelated\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\apicture\x18\x03 \x01(\tR\apicture\x12%\n" +
	"\brelation\x18\x04 \x01(\x0e2\t.RelationR\brelation\"1\n" +
	"\vAnimeStudio\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04nameB9Z7github.com/rl404/akatsuki/internal/delivery/grpc/schemab\x06proto3"

var (
	file_api_anime_proto_rawDescOnce sync.Once
	file_api_anime_proto_rawDescData []byte
)

func file_api_anime_proto_rawDescGZIP() []byte {
	file_api_anime_proto_rawDescOnce.Do(func() {
		file_api_anime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_anime_proto_rawDesc), len(file_api_anime_proto_rawDesc)))
	})
	return file_api_anime_proto_rawDescData
}

var file_api_anime_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_anime_proto_goTypes = []any{
	(*GetAnimeByIDRequest)(nil),  // 0: GetAnimeByIDRequest
	(*GetAnimeByIDResponse)(nil), // 1: GetAnimeByIDResponse
	(*Anime)(nil),                // 2: Anime
	(*AlternativeTitles)(nil),    // 3: AlternativeTitles
	(*Date)(nil),                 // 4: Date
	(*Episode)(nil),              // 5: Episode
	(*AnimeSeason)(nil),          // 6: AnimeSeason
	(*Broadcast)(nil),            // 7: Broadcast
	(*Stats)(nil),                // 8: Stats
	(*StatsStatus)(nil),          // 9: StatsStatus
	(*AnimeGenre)(nil),           // 10: AnimeGenre
	(*AnimeRelated)(nil),         // 11: AnimeRelated
	(*AnimeStudio)(nil),          // 12: AnimeStudio
	(Type)(0),                    // 13: Type
	(Status)(0),                  // 14: Status
	(Source)(0),                  // 15: Source
	(Rating)(0),                  // 16: Rating
	(Season)(0),                  // 17: Season
	(Day)(0),                     // 18: Day
	(Relation)(0),                // 19: Relation
}
var file_api_anime_proto_depIdxs = []int32{
	2,  // 0: GetAnimeByIDResponse.data:type_name -> Anime
	3,  // 1: Anime.alternative_titles:type_name -> AlternativeTitles
	4,  // 2: Anime.start_date:type_name -> Date
	4,  // 3: Anime.end_date:type_name -> Date
	13, // 4: Anime.type:type_name -> Type
	14, // 5: Anime.status:type_name -> Status
	5,  // 6: Anime.episode:type_name -> Episode
	6,  // 7: Anime.season:type_name -> AnimeSeason
	7,  // 8: Anime.broadcast:type_name -> Broadcast
	15, // 9: Anime.source:type_name -> Source
	16, // 10: Anime.rating:type_name -> Rating
	8,  // 11: Anime.stats:type_name -> Stats
	10, // 12: Anime.genres:type_name -> AnimeGenre
	11, // 13: Anime.related:type_name -> AnimeRelated
	12, // 14: Anime.studios:type_name -> AnimeStudio
	17, // 15: AnimeSeason.season:type_name -> Season
	18, // 16: Broadcast.day:type_name -> Day
	9,  // 17: Stats.status:type_name -> StatsStatus
	19, // 18: AnimeRelated.relation:type_name -> Relation
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_api_anime_proto_init() }
func file_api_anime_proto_init() {
	if File_api_anime_proto != nil {
		return
	}
	file_enum_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_anime_proto_rawDesc), len(file_api_anime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_anime_proto_goTypes,
		DependencyIndexes: file_api_anime_proto_depIdxs,
		MessageInfos:      file_api_anime_proto_msgTypes,
	}.Build()
	File_api_anime_proto = out.File
	file_api_anime_proto_goTypes = nil
	file_api_anime_proto_depIdxs = nil
}
