// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: enum.proto

package schema

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Type int32

const (
	Type_TYPE_UNKNOWN    Type = 0
	Type_TYPE_TV         Type = 1
	Type_TYPE_OVA        Type = 2
	Type_TYPE_ONA        Type = 3
	Type_TYPE_MOVIE      Type = 4
	Type_TYPE_SPECIAL    Type = 5
	Type_TYPE_MUSIC      Type = 6
	Type_TYPE_CM         Type = 7
	Type_TYPE_PV         Type = 8
	Type_TYPE_TV_SPECIAL Type = 9
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "TYPE_UNKNOWN",
		1: "TYPE_TV",
		2: "TYPE_OVA",
		3: "TYPE_ONA",
		4: "TYPE_MOVIE",
		5: "TYPE_SPECIAL",
		6: "TYPE_MUSIC",
		7: "TYPE_CM",
		8: "TYPE_PV",
		9: "TYPE_TV_SPECIAL",
	}
	Type_value = map[string]int32{
		"TYPE_UNKNOWN":    0,
		"TYPE_TV":         1,
		"TYPE_OVA":        2,
		"TYPE_ONA":        3,
		"TYPE_MOVIE":      4,
		"TYPE_SPECIAL":    5,
		"TYPE_MUSIC":      6,
		"TYPE_CM":         7,
		"TYPE_PV":         8,
		"TYPE_TV_SPECIAL": 9,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_enum_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{0}
}

type Status int32

const (
	Status_STATUS_UNKNOWN   Status = 0
	Status_STATUS_FINISHED  Status = 1
	Status_STATUS_RELEASING Status = 2
	Status_STATUS_NOT_YET   Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNKNOWN",
		1: "STATUS_FINISHED",
		2: "STATUS_RELEASING",
		3: "STATUS_NOT_YET",
	}
	Status_value = map[string]int32{
		"STATUS_UNKNOWN":   0,
		"STATUS_FINISHED":  1,
		"STATUS_RELEASING": 2,
		"STATUS_NOT_YET":   3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_proto_enumTypes[1].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_enum_proto_enumTypes[1]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{1}
}

type Season int32

const (
	Season_SEASON_UNKNOWN Season = 0
	Season_SEASON_WINTER  Season = 1
	Season_SEASON_SPRING  Season = 2
	Season_SEASON_SUMMER  Season = 3
	Season_SEASON_FALL    Season = 4
)

// Enum value maps for Season.
var (
	Season_name = map[int32]string{
		0: "SEASON_UNKNOWN",
		1: "SEASON_WINTER",
		2: "SEASON_SPRING",
		3: "SEASON_SUMMER",
		4: "SEASON_FALL",
	}
	Season_value = map[string]int32{
		"SEASON_UNKNOWN": 0,
		"SEASON_WINTER":  1,
		"SEASON_SPRING":  2,
		"SEASON_SUMMER":  3,
		"SEASON_FALL":    4,
	}
)

func (x Season) Enum() *Season {
	p := new(Season)
	*p = x
	return p
}

func (x Season) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Season) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_proto_enumTypes[2].Descriptor()
}

func (Season) Type() protoreflect.EnumType {
	return &file_enum_proto_enumTypes[2]
}

func (x Season) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Season.Descriptor instead.
func (Season) EnumDescriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{2}
}

type Day int32

const (
	Day_DAY_UNKNOWN   Day = 0
	Day_DAY_MONDAY    Day = 1
	Day_DAY_TUESDAY   Day = 2
	Day_DAY_WEDNESDAY Day = 3
	Day_DAY_THURSDAY  Day = 4
	Day_DAY_FRIDAY    Day = 5
	Day_DAY_SATURDAY  Day = 6
	Day_DAY_SUNDAY    Day = 7
	Day_DAY_OTHER     Day = 8
)

// Enum value maps for Day.
var (
	Day_name = map[int32]string{
		0: "DAY_UNKNOWN",
		1: "DAY_MONDAY",
		2: "DAY_TUESDAY",
		3: "DAY_WEDNESDAY",
		4: "DAY_THURSDAY",
		5: "DAY_FRIDAY",
		6: "DAY_SATURDAY",
		7: "DAY_SUNDAY",
		8: "DAY_OTHER",
	}
	Day_value = map[string]int32{
		"DAY_UNKNOWN":   0,
		"DAY_MONDAY":    1,
		"DAY_TUESDAY":   2,
		"DAY_WEDNESDAY": 3,
		"DAY_THURSDAY":  4,
		"DAY_FRIDAY":    5,
		"DAY_SATURDAY":  6,
		"DAY_SUNDAY":    7,
		"DAY_OTHER":     8,
	}
)

func (x Day) Enum() *Day {
	p := new(Day)
	*p = x
	return p
}

func (x Day) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Day) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_proto_enumTypes[3].Descriptor()
}

func (Day) Type() protoreflect.EnumType {
	return &file_enum_proto_enumTypes[3]
}

func (x Day) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Day.Descriptor instead.
func (Day) EnumDescriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{3}
}

type Source int32

const (
	Source_SOURCE_UNKNOWN       Source = 0
	Source_SOURCE_ORIGINAL      Source = 1
	Source_SOURCE_MANGA         Source = 2
	Source_SOURCE_4_KOMA_MANGA  Source = 3
	Source_SOURCE_WEB_MANGA     Source = 4
	Source_SOURCE_DIGITAL_MANGA Source = 5
	Source_SOURCE_NOVEL         Source = 6
	Source_SOURCE_LIGHT_NOVEL   Source = 7
	Source_SOURCE_VISUAL_NOVEL  Source = 8
	Source_SOURCE_GAME          Source = 9
	Source_SOURCE_CARD_GAME     Source = 10
	Source_SOURCE_BOOK          Source = 11
	Source_SOURCE_PICTURE_BOOK  Source = 12
	Source_SOURCE_RADIO         Source = 13
	Source_SOURCE_MUSIC         Source = 14
	Source_SOURCE_OTHER         Source = 15
	Source_SOURCE_WEB_NOVEL     Source = 16
	Source_SOURCE_MIXED_MEDIA   Source = 17
)

// Enum value maps for Source.
var (
	Source_name = map[int32]string{
		0:  "SOURCE_UNKNOWN",
		1:  "SOURCE_ORIGINAL",
		2:  "SOURCE_MANGA",
		3:  "SOURCE_4_KOMA_MANGA",
		4:  "SOURCE_WEB_MANGA",
		5:  "SOURCE_DIGITAL_MANGA",
		6:  "SOURCE_NOVEL",
		7:  "SOURCE_LIGHT_NOVEL",
		8:  "SOURCE_VISUAL_NOVEL",
		9:  "SOURCE_GAME",
		10: "SOURCE_CARD_GAME",
		11: "SOURCE_BOOK",
		12: "SOURCE_PICTURE_BOOK",
		13: "SOURCE_RADIO",
		14: "SOURCE_MUSIC",
		15: "SOURCE_OTHER",
		16: "SOURCE_WEB_NOVEL",
		17: "SOURCE_MIXED_MEDIA",
	}
	Source_value = map[string]int32{
		"SOURCE_UNKNOWN":       0,
		"SOURCE_ORIGINAL":      1,
		"SOURCE_MANGA":         2,
		"SOURCE_4_KOMA_MANGA":  3,
		"SOURCE_WEB_MANGA":     4,
		"SOURCE_DIGITAL_MANGA": 5,
		"SOURCE_NOVEL":         6,
		"SOURCE_LIGHT_NOVEL":   7,
		"SOURCE_VISUAL_NOVEL":  8,
		"SOURCE_GAME":          9,
		"SOURCE_CARD_GAME":     10,
		"SOURCE_BOOK":          11,
		"SOURCE_PICTURE_BOOK":  12,
		"SOURCE_RADIO":         13,
		"SOURCE_MUSIC":         14,
		"SOURCE_OTHER":         15,
		"SOURCE_WEB_NOVEL":     16,
		"SOURCE_MIXED_MEDIA":   17,
	}
)

func (x Source) Enum() *Source {
	p := new(Source)
	*p = x
	return p
}

func (x Source) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Source) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_proto_enumTypes[4].Descriptor()
}

func (Source) Type() protoreflect.EnumType {
	return &file_enum_proto_enumTypes[4]
}

func (x Source) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Source.Descriptor instead.
func (Source) EnumDescriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{4}
}

type Rating int32

const (
	Rating_RATING_UNKNOWN Rating = 0
	Rating_RATING_G       Rating = 1
	Rating_RATING_PG      Rating = 2
	Rating_RATING_PG13    Rating = 3
	Rating_RATING_R       Rating = 4
	Rating_RATING_R_PLUS  Rating = 5
	Rating_RATING_RX      Rating = 6
)

// Enum value maps for Rating.
var (
	Rating_name = map[int32]string{
		0: "RATING_UNKNOWN",
		1: "RATING_G",
		2: "RATING_PG",
		3: "RATING_PG13",
		4: "RATING_R",
		5: "RATING_R_PLUS",
		6: "RATING_RX",
	}
	Rating_value = map[string]int32{
		"RATING_UNKNOWN": 0,
		"RATING_G":       1,
		"RATING_PG":      2,
		"RATING_PG13":    3,
		"RATING_R":       4,
		"RATING_R_PLUS":  5,
		"RATING_RX":      6,
	}
)

func (x Rating) Enum() *Rating {
	p := new(Rating)
	*p = x
	return p
}

func (x Rating) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Rating) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_proto_enumTypes[5].Descriptor()
}

func (Rating) Type() protoreflect.EnumType {
	return &file_enum_proto_enumTypes[5]
}

func (x Rating) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Rating.Descriptor instead.
func (Rating) EnumDescriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{5}
}

type Relation int32

const (
	Relation_RELATION_UNKNOWN             Relation = 0
	Relation_RELATION_SEQUEL              Relation = 1
	Relation_RELATION_PREQUEL             Relation = 2
	Relation_RELATION_ALTERNATIVE_SETTING Relation = 3
	Relation_RELATION_ALTERNATIVE_VERSION Relation = 4
	Relation_RELATION_SIDE_STORY          Relation = 5
	Relation_RELATION_PARENT_STORY        Relation = 6
	Relation_RELATION_SUMMARY             Relation = 7
	Relation_RELATION_FULL_STORY          Relation = 8
	Relation_RELATION_SPIN_OFF            Relation = 9
	Relation_RELATION_ADAPTATION          Relation = 10
	Relation_RELATION_CHARACTER           Relation = 11
	Relation_RELATION_OTHER               Relation = 12
)

// Enum value maps for Relation.
var (
	Relation_name = map[int32]string{
		0:  "RELATION_UNKNOWN",
		1:  "RELATION_SEQUEL",
		2:  "RELATION_PREQUEL",
		3:  "RELATION_ALTERNATIVE_SETTING",
		4:  "RELATION_ALTERNATIVE_VERSION",
		5:  "RELATION_SIDE_STORY",
		6:  "RELATION_PARENT_STORY",
		7:  "RELATION_SUMMARY",
		8:  "RELATION_FULL_STORY",
		9:  "RELATION_SPIN_OFF",
		10: "RELATION_ADAPTATION",
		11: "RELATION_CHARACTER",
		12: "RELATION_OTHER",
	}
	Relation_value = map[string]int32{
		"RELATION_UNKNOWN":             0,
		"RELATION_SEQUEL":              1,
		"RELATION_PREQUEL":             2,
		"RELATION_ALTERNATIVE_SETTING": 3,
		"RELATION_ALTERNATIVE_VERSION": 4,
		"RELATION_SIDE_STORY":          5,
		"RELATION_PARENT_STORY":        6,
		"RELATION_SUMMARY":             7,
		"RELATION_FULL_STORY":          8,
		"RELATION_SPIN_OFF":            9,
		"RELATION_ADAPTATION":          10,
		"RELATION_CHARACTER":           11,
		"RELATION_OTHER":               12,
	}
)

func (x Relation) Enum() *Relation {
	p := new(Relation)
	*p = x
	return p
}

func (x Relation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Relation) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_proto_enumTypes[6].Descriptor()
}

func (Relation) Type() protoreflect.EnumType {
	return &file_enum_proto_enumTypes[6]
}

func (x Relation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Relation.Descriptor instead.
func (Relation) EnumDescriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{6}
}

type UserAnimeStatus int32

const (
	UserAnimeStatus_USER_ANIME_STATUS_UNKNOWN   UserAnimeStatus = 0
	UserAnimeStatus_USER_ANIME_STATUS_WATCHING  UserAnimeStatus = 1
	UserAnimeStatus_USER_ANIME_STATUS_COMPLETED UserAnimeStatus = 2
	UserAnimeStatus_USER_ANIME_STATUS_ON_HOLD   UserAnimeStatus = 3
	UserAnimeStatus_USER_ANIME_STATUS_DROPPED   UserAnimeStatus = 4
	UserAnimeStatus_USER_ANIME_STATUS_PLANNED   UserAnimeStatus = 5
)

// Enum value maps for UserAnimeStatus.
var (
	UserAnimeStatus_name = map[int32]string{
		0: "USER_ANIME_STATUS_UNKNOWN",
		1: "USER_ANIME_STATUS_WATCHING",
		2: "USER_ANIME_STATUS_COMPLETED",
		3: "USER_ANIME_STATUS_ON_HOLD",
		4: "USER_ANIME_STATUS_DROPPED",
		5: "USER_ANIME_STATUS_PLANNED",
	}
	UserAnimeStatus_value = map[string]int32{
		"USER_ANIME_STATUS_UNKNOWN":   0,
		"USER_ANIME_STATUS_WATCHING":  1,
		"USER_ANIME_STATUS_COMPLETED": 2,
		"USER_ANIME_STATUS_ON_HOLD":   3,
		"USER_ANIME_STATUS_DROPPED":   4,
		"USER_ANIME_STATUS_PLANNED":   5,
	}
)

func (x UserAnimeStatus) Enum() *UserAnimeStatus {
	p := new(UserAnimeStatus)
	*p = x
	return p
}

func (x UserAnimeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserAnimeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_proto_enumTypes[7].Descriptor()
}

func (UserAnimeStatus) Type() protoreflect.EnumType {
	return &file_enum_proto_enumTypes[7]
}

func (x UserAnimeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserAnimeStatus.Descriptor instead.
func (UserAnimeStatus) EnumDescriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{7}
}

var File_enum_proto protoreflect.FileDescriptor

const file_enum_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"enum.proto*\xa2\x01\n" +
	"\x04Type\x12\x10\n" +
	"\fTYPE_UNKNOWN\x10\x00\x12\v\n" +
	"\aTYPE_TV\x10\x01\x12\f\n" +
	"\bTYPE_OVA\x10\x02\x12\f\n" +
	"\bTYPE_ONA\x10\x03\x12\x0e\n" +
	"\n" +
	"TYPE_MOVIE\x10\x04\x12\x10\n" +
	"\fTYPE_SPECIAL\x10\x05\x12\x0e\n" +
	"\n" +
	"TYPE_MUSIC\x10\x06\x12\v\n" +
	"\aTYPE_CM\x10\a\x12\v\n" +
	"\aTYPE_PV\x10\b\x12\x13\n" +
	"\x0fTYPE_TV_SPECIAL\x10\t*[\n" +
	"\x06Status\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fSTATUS_FINISHED\x10\x01\x12\x14\n" +
	"\x10STATUS_RELEASING\x10\x02\x12\x12\n" +
	"\x0eSTATUS_NOT_YET\x10\x03*f\n" +
	"\x06Season\x12\x12\n" +
	"\x0eSEASON_UNKNOWN\x10\x00\x12\x11\n" +
	"\rSEASON_WINTER\x10\x01\x12\x11\n" +
	"\rSEASON_SPRING\x10\x02\x12\x11\n" +
	"\rSEASON_SUMMER\x10\x03\x12\x0f\n" +
	"\vSEASON_FALL\x10\x04*\x9d\x01\n" +
	"\x03Day\x12\x0f\n" +
	"\vDAY_UNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"DAY_MONDAY\x10\x01\x12\x0f\n" +
	"\vDAY_TUESDAY\x10\x02\x12\x11\n" +
	"\rDAY_WEDNESDAY\x10\x03\x12\x10\n" +
	"\fDAY_THURSDAY\x10\x04\x12\x0e\n" +
	"\n" +
	"DAY_FRIDAY\x10\x05\x12\x10\n" +
	"\fDAY_SATURDAY\x10\x06\x12\x0e\n" +
	"\n" +
	"DAY_SUNDAY\x10\a\x12\r\n" +
	"\tDAY_OTHER\x10\b*\x84\x03\n" +
	"\x06Source\x12\x12\n" +
	"\x0eSOURCE_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fSOURCE_ORIGINAL\x10\x01\x12\x10\n" +
	"\fSOURCE_MANGA\x10\x02\x12\x17\n" +
	"\x13SOURCE_4_KOMA_MANGA\x10\x03\x12\x14\n" +
	"\x10SOURCE_WEB_MANGA\x10\x04\x12\x18\n" +
	"\x14SOURCE_DIGITAL_MANGA\x10\x05\x12\x10\n" +
	"\fSOURCE_NOVEL\x10\x06\x12\x16\n" +
	"\x12SOURCE_LIGHT_NOVEL\x10\a\x12\x17\n" +
	"\x13SOURCE_VISUAL_NOVEL\x10\b\x12\x0f\n" +
	"\vSOURCE_GAME\x10\t\x12\x14\n" +
	"\x10SOURCE_CARD_GAME\x10\n" +
	"\x12\x0f\n" +
	"\vSOURCE_BOOK\x10\v\x12\x17\n" +
	"\x13SOURCE_PICTURE_BOOK\x10\f\x12\x10\n" +
	"\fSOURCE_RADIO\x10\r\x12\x10\n" +
	"\fSOURCE_MUSIC\x10\x0e\x12\x10\n" +
	"\fSOURCE_OTHER\x10\x0f\x12\x14\n" +
	"\x10SOURCE_WEB_NOVEL\x10\x10\x12\x16\n" +
	"\x12SOURCE_MIXED_MEDIA\x10\x11*z\n" +
	"\x06Rating\x12\x12\n" +
	"\x0eRATING_UNKNOWN\x10\x00\x12\f\n" +
	"\bRATING_G\x10\x01\x12\r\n" +
	"\tRATING_PG\x10\x02\x12\x0f\n" +
	"\vRATING_PG13\x10\x03\x12\f\n" +
	"\bRATING_R\x10\x04\x12\x11\n" +
	"\rRATING_R_PLUS\x10\x05\x12\r\n" +
	"\tRATING_RX\x10\x06*\xce\x02\n" +
	"\bRelation\x12\x14\n" +
	"\x10RELATION_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fRELATION_SEQUEL\x10\x01\x12\x14\n" +
	"\x10RELATION_PREQUEL\x10\x02\x12 \n" +
	"\x1cRELATION_ALTERNATIVE_SETTING\x10\x03\x12 \n" +
	"\x1cRELATION_ALTERNATIVE_VERSION\x10\x04\x12\x17\n" +
	"\x13RELATION_SIDE_STORY\x10\x05\x12\x19\n" +
	"\x15RELATION_PARENT_STORY\x10\x06\x12\x14\n" +
	"\x10RELATION_SUMMARY\x10\a\x12\x17\n" +
	"\x13RELATION_FULL_STORY\x10\b\x12\x15\n" +
	"\x11RELATION_SPIN_OFF\x10\t\x12\x17\n" +
	"\x13RELATION_ADAPTATION\x10\n" +
	"\x12\x16\n" +
	"\x12RELATION_CHARACTER\x10\v\x12\x12\n" +
	"\x0eRELATION_OTHER\x10\f*\xce\x01\n" +
	"\x0fUserAnimeStatus\x12\x1d\n" +
	"\x19USER_ANIME_STATUS_UNKNOWN\x10\x00\x12\x1e\n" +
	"\x1aUSER_ANIME_STATUS_WATCHING\x10\x01\x12\x1f\n" +
	"\x1bUSER_ANIME_STATUS_COMPLETED\x10\x02\x12\x1d\n" +
	"\x19USER_ANIME_STATUS_ON_HOLD\x10\x03\x12\x1d\n" +
	"\x19USER_ANIME_STATUS_DROPPED\x10\x04\x12\x1d\n" +
	"\x19USER_ANIME_STATUS_PLANNED\x10\x05B9Z7github.com/rl404/akatsuki/internal/delivery/grpc/schemab\x06proto3"

var (
	file_enum_proto_rawDescOnce sync.Once
	file_enum_proto_rawDescData []byte
)

func file_enum_proto_rawDescGZIP() []byte {
	file_enum_proto_rawDescOnce.Do(func() {
		file_enum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_enum_proto_rawDesc), len(file_enum_proto_rawDesc)))
	})
	return file_enum_proto_rawDescData
}

var file_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 8)
var file_enum_proto_goTypes = []any{
	(Type)(0),            // 0: Type
	(Status)(0),          // 1: Status
	(Season)(0),          // 2: Season
	(Day)(0),             // 3: Day
	(Source)(0),          // 4: Source
	(Rating)(0),          // 5: Rating
	(Relation)(0),        // 6: Relation
	(UserAnimeStatus)(0), // 7: UserAnimeStatus
}
var file_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_enum_proto_init() }
func file_enum_proto_init() {
	if File_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_enum_proto_rawDesc), len(file_enum_proto_rawDesc)),
			NumEnums:      8,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enum_proto_goTypes,
		DependencyIndexes: file_enum_proto_depIdxs,
		EnumInfos:         file_enum_proto_enumTypes,
	}.Build()
	File_enum_proto = out.File
	file_enum_proto_goTypes = nil
	file_enum_proto_depIdxs = nil
}
