name: tag

on: workflow_dispatch

jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go environment
      uses: actions/setup-go@v3
      with:
        go-version: 1.17
    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Create tag
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.CR_PAT }}
